// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjyeqnzzroiinlkwczxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqeWVxbnp6cm9paW5sa3djenh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzEwNDEsImV4cCI6MjA1OTk0NzA0MX0.Oo77ii1d0bDFmchWFBKT_Sj3seZGUOzy7XQR6x_StoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);